/**
 * app/partner.tsx
 * Partner Mode — Weekly Digest
 * Navigate: router.push('/partner')
 *
 * Generates a plain-language weekly summary a user can share with
 * a partner, family member, or trusted friend via the native share sheet.
 * No account needed. No data sent anywhere. Pure local → share.
 */

import { useState, useMemo } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet, Share, Switch, TextInput, Alert,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { Colors, Fonts } from '../constants/Colors';
import { useVelaStore } from '../hooks/useVelaStore';
import { PHASES } from '../constants/Data';

// ── Digest builder ─────────────────────────────────────────────────────────────

function buildDigest({
  partnerName,
  userName,
  topSymptoms,
  hotFlashDays,
  avgSleep,
  streak,
  phase,
  suppAdherence,
  includeSymptoms,
  includeSleep,
  includeSupps,
  includeWhatHelps,
}: {
  partnerName: string;
  userName: string;
  topSymptoms: { symptom: string; count: number }[];
  hotFlashDays: number;
  avgSleep: number | null;
  streak: number;
  phase: string;
  suppAdherence: number;
  includeSymptoms: boolean;
  includeSleep: boolean;
  includeSupps: boolean;
  includeWhatHelps: boolean;
}): string {
  const phaseLabels: Record<string, string> = {
    early: 'early perimenopause', mid: 'mid perimenopause',
    late: 'late perimenopause', post: 'post-menopause',
  };
  const phaseLabel = phaseLabels[phase] ?? 'perimenopause';
  const greeting = partnerName ? `Hi ${partnerName},` : 'Hi,';
  const name = userName || 'I';

  const lines = [
    `${greeting}`,
    '',
    `${name === 'I' ? 'Here is' : `${userName} is sharing`} a quick update from Vela — a perimenopause wellness app ${name === 'I' ? 'I use' : 'she uses'} to track symptoms and health patterns.`,
    '',
    `📍 ${name === 'I' ? 'I am' : 'She is'} currently in ${phaseLabel}. This is a real hormonal transition — not stress, not aging "gracefully." It involves measurable changes in estrogen and progesterone that affect sleep, temperature regulation, mood, memory, and energy.`,
    '',
  ];

  if (includeSymptoms && topSymptoms.length > 0) {
    lines.push('🔴 THIS WEEK\'S SYMPTOMS');
    topSymptoms.slice(0, 5).forEach(s => {
      lines.push(`• ${s.symptom}: ${s.count} days this week`);
    });
    if (hotFlashDays > 0) {
      lines.push(`• Hot flashes: ${hotFlashDays} days (these are sudden waves of heat — ${name === 'I' ? 'I' : 'she'} cannot control them and they can happen anytime)`);
    }
    lines.push('');
  }

  if (includeSleep) {
    lines.push('😴 SLEEP');
    if (avgSleep !== null) {
      const sleepDesc = avgSleep >= 4 ? 'relatively good' : avgSleep >= 3 ? 'okay' : avgSleep < 2 ? 'very poor' : 'disrupted';
      lines.push(`Sleep quality averaged ${avgSleep}/5 this week — ${sleepDesc}.`);
      if (avgSleep < 3) {
        lines.push(`Night sweats often wake ${name === 'I' ? 'me' : 'her'} up. This is not insomnia — it is a physiological response to hormonal changes. ${name === 'I' ? 'I am' : 'She is'} managing it but may be more tired than usual.`);
      }
    } else {
      lines.push('Sleep data not logged this week.');
    }
    lines.push('');
  }

  if (includeSupps) {
    lines.push('💊 SUPPLEMENTS & SELF-CARE');
    lines.push(`${name === 'I' ? 'I' : 'She'} took ${name === 'I' ? 'my' : 'her'} evidence-based supplements ${suppAdherence}% of days this week.`);
    if (streak >= 7) {
      lines.push(`${streak}-day wellness streak — that is real consistency.`);
    }
    lines.push('');
  }

  if (includeWhatHelps) {
    lines.push('💙 WHAT HELPS');
    lines.push(`• Acknowledging that ${name === 'I' ? 'I am' : 'she is'} managing something real, not "just hormones"`);
    lines.push(`• Patience when ${name === 'I' ? 'I am' : 'she is'} tired or irritable — it is physiological, not personal`);
    lines.push(`• Keeping the bedroom cool at night (below 65°F if possible)`);
    lines.push(`• Not offering solutions when ${name === 'I' ? 'I' : 'she'} just needs to be heard`);
    lines.push(`• Asking "how are you feeling today?" and meaning it`);
    lines.push('');
  }

  lines.push('This update was generated by Vela Wellness — an app designed to track perimenopause symptoms and help women navigate this transition with data and support.');
  lines.push('');
  lines.push('Thank you for being someone worth sharing this with. 🤍');

  return lines.join('\n');
}

// ── Main screen ────────────────────────────────────────────────────────────────

export default function PartnerScreen() {
  const { history, sleepHistory, streak, phase, suppAdherence } = useVelaStore();
  const pd = PHASES[phase ?? 'late'];

  const [partnerName, setPartnerName] = useState('');
  const [userName, setUserName] = useState('');
  const [includeSymptoms, setIncludeSymptoms] = useState(true);
  const [includeSleep, setIncludeSleep] = useState(true);
  const [includeSupps, setIncludeSupps] = useState(true);
  const [includeWhatHelps, setIncludeWhatHelps] = useState(true);
  const [preview, setPreview] = useState(false);

  // Last 7 days
  const topSymptoms = useMemo(() => {
    const cutoff = new Date(); cutoff.setDate(cutoff.getDate() - 7);
    const recent = history.filter(h => new Date(h.date) >= cutoff);
    const counts: Record<string, number> = {};
    recent.forEach(h => (h.symptoms ?? []).forEach((s: string) => { counts[s] = (counts[s] ?? 0) + 1; }));
    return Object.entries(counts).sort((a, b) => b[1] - a[1]).slice(0, 6).map(([symptom, count]) => ({ symptom, count }));
  }, [history]);

  const hotFlashDays = useMemo(() => {
    const cutoff = new Date(); cutoff.setDate(cutoff.getDate() - 7);
    return history.filter(h => new Date(h.date) >= cutoff && h.symptoms?.includes('Hot flash')).length;
  }, [history]);

  const avgSleep = useMemo(() => {
    const recent = sleepHistory.slice(0, 7);
    if (recent.length === 0) return null;
    return Math.round(recent.reduce((a, s: any) => a + (s.quality ?? 0), 0) / recent.length * 10) / 10;
  }, [sleepHistory]);

  const digest = useMemo(() => buildDigest({
    partnerName, userName,
    topSymptoms, hotFlashDays, avgSleep, streak,
    phase: phase ?? 'late',
    suppAdherence: suppAdherence(),
    includeSymptoms, includeSleep, includeSupps, includeWhatHelps,
  }), [partnerName, userName, topSymptoms, hotFlashDays, avgSleep, streak, phase, suppAdherence, includeSymptoms, includeSleep, includeSupps, includeWhatHelps]);

  const handleShare = async () => {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    try {
      await Share.share({ message: digest, title: 'Vela Weekly Update' });
    } catch (e) {
      Alert.alert('Could not share', 'Please try again.');
    }
  };

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={{ padding: 4 }}>
          <Text style={styles.back}>←</Text>
        </TouchableOpacity>
        <View style={{ flex: 1 }}>
          <Text style={styles.title}>Partner Mode</Text>
          <Text style={styles.titleSub}>Share your week with someone you trust</Text>
        </View>
      </View>

      <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 120 }} showsVerticalScrollIndicator={false}>

        {/* Intro */}
        <View style={[styles.card, { backgroundColor: Colors.plum }]}>
          <Text style={{ fontFamily: Fonts.serif, fontSize: 18, color: Colors.parchment, lineHeight: 26, marginBottom: 8 }}>
            You don't have to navigate this alone.
          </Text>
          <Text style={{ fontFamily: Fonts.sans, fontSize: 13, color: 'rgba(245,239,230,0.75)', lineHeight: 20 }}>
            Generate a plain-language weekly update for a partner, family member, or close friend. Nothing medical — just what your week actually looked like, in words they can understand.
          </Text>
        </View>

        {/* Names */}
        <View style={styles.card}>
          <Text style={styles.fieldLabel}>Who are you sharing with? (optional)</Text>
          <TextInput style={styles.input} value={partnerName} onChangeText={setPartnerName}
            placeholder="Partner's name" placeholderTextColor={Colors.mist} />
          <Text style={[styles.fieldLabel, { marginTop: 8 }]}>Your name (optional)</Text>
          <TextInput style={styles.input} value={userName} onChangeText={setUserName}
            placeholder="Your name" placeholderTextColor={Colors.mist} />
        </View>

        {/* What to include */}
        <View style={styles.card}>
          <Text style={styles.sectionLabel}>What to include</Text>
          {[
            { label: 'Symptoms this week', sub: `${topSymptoms.length} symptoms tracked`, value: includeSymptoms, set: setIncludeSymptoms },
            { label: 'Sleep patterns', sub: avgSleep !== null ? `Avg ${avgSleep}/5 this week` : 'Log sleep to include', value: includeSleep, set: setIncludeSleep },
            { label: 'Supplements & streak', sub: `${suppAdherence()}% adherence · ${streak} day streak`, value: includeSupps, set: setIncludeSupps },
            { label: '"What helps" guide', sub: 'Practical tips for your partner', value: includeWhatHelps, set: setIncludeWhatHelps },
          ].map(item => (
            <View key={item.label} style={styles.toggleRow}>
              <View style={{ flex: 1 }}>
                <Text style={styles.toggleLabel}>{item.label}</Text>
                <Text style={styles.toggleSub}>{item.sub}</Text>
              </View>
              <Switch value={item.value} onValueChange={item.set}
                trackColor={{ false: Colors.parchmentDark, true: Colors.sage }}
                thumbColor={Colors.cream} />
            </View>
          ))}
        </View>

        {/* Preview toggle */}
        <TouchableOpacity style={styles.previewBtn} onPress={() => setPreview(p => !p)} activeOpacity={0.8}>
          <Text style={styles.previewBtnText}>{preview ? 'Hide preview' : 'Preview digest'}</Text>
        </TouchableOpacity>

        {preview && (
          <View style={[styles.card, { backgroundColor: Colors.parchment }]}>
            <Text style={{ fontFamily: Fonts.sans, fontSize: 12, color: Colors.plum, lineHeight: 20 }}>{digest}</Text>
          </View>
        )}

        {/* This week's data */}
        <View style={styles.card}>
          <Text style={styles.sectionLabel}>Your week at a glance</Text>
          <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: topSymptoms.length > 0 ? 14 : 0 }}>
            {[
              { label: 'Symptoms', value: String(topSymptoms.reduce((a, s) => a + s.count, 0)), color: Colors.rose },
              { label: 'Hot flash days', value: String(hotFlashDays), color: Colors.rose },
              { label: 'Avg sleep', value: avgSleep !== null ? `${avgSleep}/5` : '—', color: Colors.teal },
              { label: 'Streak', value: `${streak}d`, color: Colors.gold },
            ].map(s => (
              <View key={s.label} style={styles.statCard}>
                <Text style={[styles.statNum, { color: s.color }]}>{s.value}</Text>
                <Text style={styles.statLabel}>{s.label}</Text>
              </View>
            ))}
          </View>
          {topSymptoms.length > 0 && (
            <>
              <Text style={[styles.sectionLabel, { marginBottom: 8 }]}>Top symptoms this week</Text>
              {topSymptoms.slice(0, 4).map(s => (
                <View key={s.symptom} style={{ flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottomWidth: 0.5, borderBottomColor: Colors.parchmentDark }}>
                  <Text style={{ fontFamily: Fonts.sans, fontSize: 13, color: Colors.plum }}>{s.symptom}</Text>
                  <Text style={{ fontFamily: Fonts.sans, fontSize: 13, color: Colors.rose }}>{s.count} days</Text>
                </View>
              ))}
            </>
          )}
          {topSymptoms.length === 0 && (
            <Text style={{ fontFamily: Fonts.sans, fontSize: 13, color: Colors.mist }}>
              Log symptoms in your Ritual tab this week to populate this section.
            </Text>
          )}
        </View>

        {/* Privacy note */}
        <View style={[styles.card, { backgroundColor: Colors.sagePale, borderColor: Colors.sage + '30' }]}>
          <Text style={{ fontFamily: Fonts.sansMedium, fontSize: 10, color: Colors.sage, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 6 }}>
            🔒 Your privacy
          </Text>
          <Text style={{ fontFamily: Fonts.sans, fontSize: 12, color: Colors.plum, lineHeight: 19 }}>
            The digest is generated entirely on your device. Nothing is sent to any server. You choose what to share, with whom, and when — using your phone's native share sheet.
          </Text>
        </View>

      </ScrollView>

      {/* Sticky share button */}
      <View style={styles.stickyBar}>
        <TouchableOpacity style={styles.shareBtn} onPress={handleShare} activeOpacity={0.85}>
          <Text style={styles.shareBtnText}>Share weekly digest →</Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

// ── Styles ─────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  safe:        { flex: 1, backgroundColor: Colors.parchment },
  header:      { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 20, paddingTop: 12, paddingBottom: 14, backgroundColor: Colors.plum },
  back:        { fontFamily: Fonts.sans, fontSize: 20, color: Colors.goldLight },
  title:       { fontFamily: Fonts.serif, fontSize: 18, color: Colors.goldLight },
  titleSub:    { fontFamily: Fonts.sans, fontSize: 11, color: Colors.mist, marginTop: 1 },
  card:        { backgroundColor: Colors.cream, borderWidth: 0.5, borderColor: Colors.parchmentDark, borderRadius: 18, padding: 18, marginBottom: 14 },
  sectionLabel:{ fontFamily: Fonts.sansMedium, fontSize: 10, color: Colors.mist, letterSpacing: 2, textTransform: 'uppercase', marginBottom: 10 },
  fieldLabel:  { fontFamily: Fonts.sansMedium, fontSize: 11, color: Colors.mist, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 6 },
  input:       { backgroundColor: Colors.parchment, borderWidth: 0.5, borderColor: Colors.parchmentDark, borderRadius: 12, padding: 12, fontFamily: Fonts.sans, fontSize: 14, color: Colors.plum },
  toggleRow:   { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, borderBottomWidth: 0.5, borderBottomColor: Colors.parchmentDark, gap: 12 },
  toggleLabel: { fontFamily: Fonts.sansMedium, fontSize: 14, color: Colors.plum, marginBottom: 2 },
  toggleSub:   { fontFamily: Fonts.sans, fontSize: 11, color: Colors.mist },
  previewBtn:  { borderWidth: 0.5, borderColor: Colors.plum, borderRadius: 20, paddingVertical: 10, alignItems: 'center', marginBottom: 14 },
  previewBtnText: { fontFamily: Fonts.sansMedium, fontSize: 13, color: Colors.plum },
  statCard:    { flex: 1, minWidth: '45%', backgroundColor: Colors.parchment, borderRadius: 12, padding: 12, alignItems: 'center', borderWidth: 0.5, borderColor: Colors.parchmentDark },
  statNum:     { fontFamily: Fonts.serif, fontSize: 22, marginBottom: 3 },
  statLabel:   { fontFamily: Fonts.sans, fontSize: 10, color: Colors.mist, textAlign: 'center' },
  stickyBar:   { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 20, paddingBottom: 36, backgroundColor: Colors.parchment, borderTopWidth: 0.5, borderTopColor: Colors.parchmentDark },
  shareBtn:    { backgroundColor: Colors.plum, borderRadius: 20, paddingVertical: 16, alignItems: 'center' },
  shareBtnText:{ fontFamily: Fonts.sansMedium, fontSize: 15, color: Colors.parchment },
});
